apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: sba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: sit-bmw-model
          image: registry.cn-hangzhou.aliyuncs.com/dev_savage/sba-eureka:{version}
          ports:
            - name: http-port
              containerPort: 10001
          env:
            - name: spring_profiles_active
              value: k8s
      imagePullSecrets:
        - name: sbasecret